#!/bin/bash

set -u


print_version_by_tag() {
  git describe --tags --exact-match --dirty --match 'v*' 2>/dev/null \
    | awk -F '-' -v OFS='-' '
        BEGIN { found=0 };
        {
          sub(/^v/, "", $1);
          if ($NF != "dirty") {
            print $0;
            found=1
          }
        };
        END {
          if (!found) {
            exit 1
          }
        }'
}


main() {
  print_version_by_tag || echo 'unknown'
}


main "$@"
